namespace Adanom.Ecommerce.API.Data.Models
{
    public enum EntityType : byte
    {
        PRODUCT,
        PRODUCTCATEGORY,
        PRODUCTATTRIBUTE,
        PRODUCTSKU,
        PRODUCTPRICE,
        PRODUCTSPECIFICATIONATTRIBUTE,
        PRODUCTSPECIFICATIONATTRIBUTEGROUP,
        PRODUCTTAG,
        PRODUCT_PRODUCTCATEGORY,
        PRODUCT_PRODUCTSPECIFICATIONATTRIBUTE,
        PRODUCT_PRODUCTTAG,
        BRAND,
        TAXCATEGORY,
        NOTIFICATION,
        METAINFORMATION,
        IMAGE,
        PRODUCTREVIEW,
        TAXADMINISTRATION,
        SLIDERITEM,
        COMPANY,
        SHIPPINGPROVIDER,
        PICKUPSTORE
    }
}
