namespace Adanom.Ecommerce.API.Data.Models
{
    public enum MailTemplateKey : byte
    {
        AUTH_NEW_USER,
        AUTH_EMAIL_CONFIRMATION,
        AUTH_EMAIL_CONFIRMED_SUCCESSFUL,
        AUTH_PASSWORD_CHANGED_SUCCESSFUL,
        AUTH_PASSWORD_RESET,
        AUTH_PASSWORD_RESET_SUCCESSFUL,
        ORDER_ORDERSTATUSTYPE_IN_PROGRESS,
        ORDER_ORDERSTATUSTYPE_READY_PICK_UP_FROM_STORE,
        ORDER_ORDERSTATUSTYPE_DELIVERED_TO_SHIPPING_PROVIDER_CARGO_SHIPMENT,
        ORDER_ORDERSTATUSTYPE_DELIVERED_TO_CUSTOMER,
        ORDER_ORDERSTATUSTYPE_CANCEL
    }
}
