namespace Adanom.Ecommerce.API.Data.Models
{
    public enum MailTemplateKey : byte
    {
        WELCOME,
        EMAIL_CONFIRMATION,
        EMAIL_CONFIRMED_SUCCESSFUL,
        PASSWORD_CHANGED_SUCCESSFUL,
        PASSWORD_RESET,
        PASSWORD_RESET_SUCCESSFUL,
        ORDER_ORDERSTATUSTYPE_IN_PROGRESS,
        ORDER_ORDERSTATUSTYPE_READY_PICK_UP_FROM_STORE,
        ORDER_ORDERSTATUSTYPE_DELIVERED_TO_SHIPPING_PROVIDER_CARGO_SHIPMENT,
        ORDER_ORDERSTATUSTYPE_DELIVERED_TO_CUSTOMER,
        ORDER_ORDERSTATUSTYPE_CANCEL
    }
}
