global using Microsoft.EntityFrameworkCore;
global using Adanom.Ecommerce.API.Commands;
global using Adanom.Ecommerce.API.Commands.Models;
global using Adanom.Ecommerce.API.Data;
global using Adanom.Ecommerce.API.Data.Models;
global using Adanom.Ecommerce.API.Pagination;
global using HotChocolate;
global using MediatR;
global using AutoMapper;